# Generated by Django 5.2.1 on 2025-05-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
