# Generated by Django 5.2.1 on 2025-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_data', '0002_alter_person_dob_alter_person_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='dod',
            field=models.IntegerField(),
        ),
    ]
